sudo: required 
servcies: 
    - docker 

before_install: 
    - docker build -t kailiang1/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true kailiang1/docker-react npm run test

language: generic 
